version: '3.7'
services:
  rendertron:
    image: experiusnl/rendertron:latest
    container_name: rendertron
    restart: always
    volumes:
      - ./rendertron-config.json:/app/config.json
    ports:
      - 3000:3000
    networks:
      - rendertron_net

networks:
  rendertron_net:
    driver: bridge
